### PR TITLE
Support for Bitwise Operations as InfixOperations

### PR DESCRIPTION
**Pull request by sjaveed**
** This PR is closed in lieu of the cleaner #408 **

I've added support for bitwise AND, OR, XOR, left shift and right shift as infix operations.  This PR contains the new functionality, tests and documentation updates.

#### Examples ####
```ruby
users.where((users[:bitmap] & 16).gt(0)).project(Arel.sql('*')) # => SELECT * FROM "users"  WHERE ("users"."bitmap" & 16) > 0
users.where((users[:bitmap] | 16).gt(0)).project(Arel.sql('*')) # => SELECT * FROM "users"  WHERE ("users"."bitmap" | 16) > 0
users.where((users[:bitmap] ^ 16).gt(0)).project(Arel.sql('*')) # => SELECT * FROM "users"  WHERE ("users"."bitmap" ^ 16) > 0
users.where((users[:bitmap] << 1).gt(0)).project(Arel.sql('*')) # => SELECT * FROM "users"  WHERE ("users"."bitmap" << 1) > 0
users.where((users[:bitmap] >> 1).gt(0)).project(Arel.sql('*')) # => SELECT * FROM "users"  WHERE ("users"."bitmap" >> 1) > 0
```

#### Questions: ####
* Is this useful to anyone else?
* Should I implement this in a different way?
* How do I implement the bitwise NOT operator (~) which is unary?

Thanks!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
> How do I implement the bitwise NOT operator (~) which is unary?

I don't know if ruby support unary methods but for arel you could define a method in the node. `users[:bitmap].bitwise_not` or some other name.

**Comment by ernie** [comment]
@rafaelfranca you can define unary `~` via:

```ruby
def ~@
  something_interesting
end
```

**Comment by rafaelfranca** [comment]
Oh, that is cool. Thanks!

**Comment by ernie** [comment]
@rafaelfranca Any time. `<operator_name>@` works for any unary operators I'm aware of.

**Comment by sjaveed** [comment]
I just need it for Arel so I'll see how to define it on the node.  Everything else looks OK though @rafaelfranca and @ernie?  In some ways I'm more interested in making sure the specs for these operators are testing the right thing properly.

Thanks!

**Comment by sjaveed** [comment]
@rafaelfranca I just added a UnaryOperation class (inspired by InfixOperation) that that provides unary operations.  Test are in place.  Is this the right approach to this?  I'll push out an update to documentation in the next few minutes.

Your suggestion about how to implement a unary operator was very helpful @ernie :-)

**Comment by sjaveed** [comment]
Looks like an issue running tests under jruby-head only.

**Comment by sjaveed** [comment]
Rebased on upstream/master but jruby-head continues to fail.  Thoughts @rafaelfranca?

**Comment by ernie** [comment]
@sjaveed I'm not @rafaelfranca, but looking at that failure it looks to be an issue with the `bundle` command on the machine itself and not specifically with your code. Have you tried testing against jruby locally?

**Comment by sjaveed** [comment]
@ernie no I haven't.  I'll do that now!

**Comment by sjaveed** [comment]
Locally ```bundle install``` fails with a different message:
```
sjaveed@braavosi:arel [bitwise_ops] [jruby-head@arel]$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2
Using arel 7.0.0 from source at `.`
Using minitest 5.8.3
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
section: 'json'
```
That last bit seems odd.  I'll dig deeper.

**Comment by sjaveed** [comment]
I ended up manually re-basing my commits on top of the latest master and all looks great.  Closing this in lieu of #408 where all specs are passing.

**Pull request closed without merging**
