### PR TITLE
Add temporary tables

### PR DESCRIPTION
**Pull request by alexmobo**
With this we could do something like
```ruby
clients = Arel::Subquery.new('SELECT * FROM users WHERE type="client"', as: 'clients')
```
or
```ruby
users = Arel::Table.new(:users)
clients = Arel::Subquery.new(users.project(Arel.star).where(users[:type].eq('type')), as: 'clients')
```
to do something like
```ruby
clients.project(Arel.star)
```
to produce the sql next output
```sql
SELECT * FROM (SELECT * FROM users WHERE type="client") clients
```

also if we write something like
```ruby
clients = Arel::Subquery.new('SELECT * FROM users')
```
without the `as` keyword argument, we get the same as before but with a 10-length random name for the table (i.e.)
```sql
SELECT * FROM (SELECT * FROM users) htjdnyehrn
```

### CODE REVIEW

**Comment by mstahl** [comment]
👍

**Comment by webandtech** [comment]
👍

**Comment by bdevel** [comment]
Technically speaking, that SQL is not making a temporary table - it is a subquery. As such, I would recommend re-naming the class to `Arel::Subquery` and reserve `Arel::TemporaryTable` for true temporary tables to avoid confusion.

Further, theres more than one way to create temporary tables (depending on db provider). Examples: 
  * `SELECT id INTO TEMPORARY TABLE tmp_ids FROM foos`
  * `CREATE TEMPORARY TABLE tmp_ids AS SELECT id FROM foos`

Currently, I'm currently having trouble using AREL to create such a temporary table with AREL when common table expressions (CTE) have been applied.

**Comment by alexmobo** [comment]
I have changed `TemporaryTable` to `Subquery` as @bdevel commented.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this PR is still relevant, please consider reopening it over there.

**Pull request closed without merging**
