### PR TITLE
Follow up #370 for Oracle, to fix undefined method `expr' for 10:Fixnum bug.

### PR DESCRIPTION
**Pull request by Eric-Guo**
@rafaelfranca 
per @yahonda suggestion at #376, try to fix at master branch first and backport into `6-0-stable` branch.

### CODE REVIEW

**Comment by jakevose** [comment]
We ran into this issue trying to use `kaminari` or `will_paginate` with `activerecord-oracle_enhanced-adapter` — both gems call `.limit` and `.offset` in combination. Thanks for fixing!

**Comment by yahonda** [comment]
@rafaelfranca Would you consider to release the next version of Arel 6.0.3 including this fix since there is another issue reported https://github.com/rsim/oracle-enhanced/issues/678 . Thanks in advance.

**Comment by rafaelfranca** [comment]
Sure. Let me review the last commits and see if I need to backport something else.

**Comment by yahonda** [comment]
Thank you.

**Pull request merged**
