### PR TITLE
Do not bug when range ends at Date::Infinity

### PR DESCRIPTION
**Pull request by tadeusrox**
First of all this is my very first open source pull request I am learning the flow :) 

This pull request try to fix the issue reported in

https://github.com/rails/rails/issues/22599

### CODE REVIEW

**Comment by sgrif** [comment]
Thanks, but many backends do support this.

**Comment by sgrif** [comment]
This should error on backends for which it is unsupported, however

**Comment by tadeusrox** [comment]
What do you mean when you are referring to 'backends' ?

**Comment by kbrock** [comment]
@sgrif Could you share what you mean? Do you mean that in the current implementations, the databases servers output the correct sql with a greater than?

@matthewd After reading about deprecating `Date::Infinity`, are you suggesting using `other.end.infinite?` instead? (are you surprised I stumbled upon this pr? :) )

**Comment by sgrif** [comment]
PostgreSQL (and Oracle I think) do support infinite dates, and we should
continue to maintain the current behavior for them.

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this PR is still relevant, please consider reopening it over there.

**Pull request closed without merging**
