### PR TITLE
Add Regexp and NotRegexp support for MySQL.

### PR DESCRIPTION
**Pull request by JacobEvelyn**
Code shamelessly stolen from https://github.com/rails/arel/commit/6296617c159d5cee0ba1c76f4ea983e3b5e26b6b

### CODE REVIEW

**Comment by imajes** [comment]
This looks really good to me, and I just tested this on a project requiring it. I say go ahead with a merge. :+1:

**Comment by caldwecr** [comment]
Eta on this getting into the main branch?

**Comment by kbrock** [comment]
@JacobEvelyn could you test this with `matches`?

```ruby
node = @table[:name].matches(Nodes.build_quoted('foo%'))
compile(node).must_be_like %{
  "users"."name" REGEXP 'foo%'
}
```

And is that supposed to be `'foo.*'` or is `'foo%'` correct?
Will this work in rails, or does some conversion need to take place? (e.g.: `User.where(name: /foo.*/)`)

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this PR is still relevant, please consider reopening it over there.

**Pull request closed without merging**
