### PR TITLE
No need to quote MySQL LIMIT

### PR DESCRIPTION
**Pull request by byroot**
Followup to https://github.com/arthurnn/arel/commit/334589cc532a6e8f780b9af1b8492d7b8dfdbd1f

This static limit doesn't need to be quoted either.

@arthurnn @rafaelfranca @tenderlove for review please.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Better to get @arthurnn's commit too since I think he didn't send to upstream yet.

**Comment by rafaelfranca** [comment]
Ah, he did.

**Comment by arthurnn** [comment]
can we backport this and my commit to 6.x?

**Comment by byroot** [comment]
@arthurnn they are in `6.0.1`

**Pull request merged**
