### PR TITLE
support MySQL and PostgreSQL extended DELETE syntax

### PR DESCRIPTION
**Pull request by ccutrer**
note that this also adds support for limit on all adapters by doing a subquery (just like update)

### CODE REVIEW

**Comment by tamird** [comment]
@ccutrer https://github.com/rails/arel/pull/356 was just merged, can you rebase?

**Comment by tamird** [comment]
@ccutrer can you squash the relevant parts of the last commit into the other two? the changes look good to me, @rafaelfranca can you please triage?

**Comment by ccutrer** [comment]
@tamird - squashed down to two commits.

**Comment by tamird** [comment]
would love to see this get in :+1: cc @tenderlove

**Comment by tenderlove** [comment]
LGTM, but @sgrif can you review?

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this PR is still relevant, please consider reopening it over there.

**Pull request closed without merging**
