### PR TITLE
added math to function nodes

### PR DESCRIPTION
**Pull request by romankonz**

### CODE REVIEW

**Comment by kbrock** [comment]
@romankonz have you tested after https://github.com/rails/arel/pull/449 was merged?

Wonder if it just works now

**Comment by nikolai-b** [comment]
@kbrock Just tested the SUM (as math was explicitly added to `count`  1aeefa68)
At 5f25b0a it errors with

```
Error:
Arel::Nodes::Sum::math#test_0001_should be able to use math operators:
NoMethodError: undefined method `-' for #<Arel::Nodes::Avg:0x0055f182205b10>
    ./arel/test/nodes/test_sum.rb:38:in `block (3 levels) in <top (required)>'
```
and after #449 (i.e. aa11ad91) it passes.

**Comment by kbrock** [comment]
@nikolai-b thanks

Curious if `count` node still needs `Math` mixed in. but oh well. glad it was working for you

**Comment by matthewd** [comment]
Per #523, Arel development is moving to [rails/rails](https://github.com/rails/rails).

If this PR is still relevant, please consider reopening it over there.

**Pull request closed without merging**
